### ISSUE TITLE
The user can create the Kafka destination connector with an invalid value "-1"

### ISSUE THREAD

**Issue by uchennakevinm1** [ConduitIO/conduit-kafka-connect-wrapper#122]

**Comment by hariso** [comment]
Based on the title, it looks like this is about the Kafka connector, not this Kafka Connect wrapper? Also, we should specify for what field is -1 an invalid value.

**Comment by lovromazgon** [comment]
This was opened by mistake, the actual issue is https://github.com/ConduitIO/conduit-connector-kafka/issues/42.
