### ISSUE TITLE
Test more sources and destinations

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit-kafka-connect-wrapper#27]
- [x] JDBC connectors (by Aiven): source and destination, MySQL and Postgres
- [x] Debezium connectors: MySQL, Postgres
- [x] Snowflake
- [x] HTTP ([source](https://github.com/castorm/kafka-connect-http), [sink](https://github.com/thomaskwscott/kafka-connect-http/))
- [x] File (source, sink)

**Comment by hariso** [comment]
CosmosDB tested last week too. Both source and destination worked.

**Comment by hariso** [comment]
@neovintage Do you think we can close this one?

**Comment by neovintage** [comment]
@hariso close it!
