### ISSUE TITLE
Feature: Script to download a connector JAR with all of its dependencies

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit-kafka-connect-wrapper#47]
### Feature description

The wrapper makes it possible to load connector JARs from a directory (`lib`). In case the connector JAR has dependencies, the dependencies too need to be downloaded.

For a better experience with this wrapper, we should provide a script which will download a connector JAR from a Maven repo, together with all of its dependencies. 

Example: running something like `./get-jar.sh connector-xyz:1.2.3 download-dir/` would download connector-xyz:1.2.3 from a Maven repo, all of its dependencies and save them to a `download-dir/`.

**Comment by neovintage** [comment]
@samirketema @lyuboxa Do we manually get all of the dependencies to put into the meroxa platform?

**Comment by samirketema** [comment]
@neovintage We are just using the conduit binary with the built-in connectors. We aren't using the kafka-connect wrapper

**Comment by samirketema** [comment]
I see, I realize I was talking more about the conduit connector configuration and less about how we are running existing (non-conduit) connectors in the platform - @lyuboxa do you know how we currently do this in platform?
