### ISSUE TITLE
Feature: Leveled logging 

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit-kafka-connect-wrapper#48]
### Feature description

The logs the wrapper sends to Conduit (implemented in #43) are sent with an "unknown" logging level (i.e. the logging level is `???`). It would be good to have proper, leveled, logs.

Additional info about the current logging implementation: https://github.com/ConduitIO/conduit-kafka-connect-wrapper/pull/43#discussion_r836684780

**Comment by lovromazgon** [comment]
More info on how logging works in go-plugin gRPC plugins and reasoning why https://github.com/hashicorp/go-plugin/pull/135#issuecomment-590518189.
