### ISSUE TITLE
Schema generation: Handle structs with heterogeneous list fields

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit-kafka-connect-wrapper#61]
### Feature description

When auto-generating a schema for a Protobuf struct (used for structured Conduit records), we generate a schema for its list field(s). Currently, we assume that the list is homogeneous, however, they do not have to be. As seen in the docs [here](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.ListValue), a list may contain any type of value.

**Comment by lovromazgon** [comment]
Will not extend auto generation, but rather tackle this once Conduit records support schemas.
