### ISSUE TITLE
Feature: Changes to Source.Stop

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit-kafka-connect-wrapper#65]
### Feature description

The position of the last record read from a source should be sent back in Source.Stop. 

See: https://github.com/ConduitIO/conduit/issues/391

**Comment by uchennakevinm1** [comment]
Changes to the kafka connect wrapper! High priority once we complete the following dependencies.

Dependent on:
1. [OpenCDC changes](https://github.com/ConduitIO/conduit/issues/422)
2. [Pipeline stability issues](https://github.com/ConduitIO/conduit/issues/389)

**Comment by hariso** [comment]
Fixed in #121.
